[project]
name = "simple-ai-agent"
version = "1.0.0"
description = "AI Agent API with FastAPI and LangChain"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Emanuel Cortez", email="emanuelcortez32@gmail.com" }
]

dependencies = [
    "langchain==1.2.10",
    "langchain-community==0.3.31",
    "langchain-ollama==1.0.1",
    "fastapi[standard]==0.128.0",
    "pydantic==2.12.5",
    "pydantic-settings>=2.10.1",
    "python-dotenv==1.2.2",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=5.0.0"
]

[tool.pytest_env]

[tool.hatch.build.targets.wheel]
packages = ["src*"]
