[project]
name = "prompt-injector-defender"
version = "1.0.0"
description = "Prompt Injector Defender"
requires-python = ">=3.11"
authors = [
    { name = "Emanuel Cortez", email = "emanuelcortez32@gmail.com" }
]
dependencies = [
    "ipykernel==7.1.0",
    "joblib==1.5.3",
    "matplotlib==3.10.8",
    "pandas==2.3.3",
    "pyarrow==23.0.1",
    "scikit-learn==1.8.0",
    "skl2onnx==1.19.1",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["."]


[tool.hatch.build.targets.wheel]
packages = ["."]
